name: Publish Addon Action

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get sources
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Debug
      - name: Where am I ? üßê
        run: ls -la ./
      # Package the plugin
      - name: üî• Starting Zipping
        run: zip AutoSciHubAuto.zip ./assets/* ./icons/* ./manifest.json ./shRedirect.js
      # Upload on Firefox
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{be4c6348-e64f-4ff9-9e48-47468de8aa64}'
          xpi: AutoSciHubAuto.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
        continue-on-error: false
      # Upload on Chrome Store
      #- uses: trmcnvn/chrome-addon@v1
      #  with:
      #    extension: nlogbpfgpkffmombiknfdoogphkimmmd
      #    zip: AutoSciHubAuto.zip
      #    client-id: ${{ secrets.CHROME_CLIENT_ID }}
      #    client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      #    refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      #  continue-on-error: true
